global:
  security:
    allowInsecureImages: True
image:
  registry: docker.io
  tag: latest
  repository: bitnamilegacy/mysql 

global:
  defaultStorageClass: gp2

primary: 
  persistence: 
    enabled: true 
    storageClass: gp2

secondary:
  replicaCount: 2
  persistence: 
    enabled: true
    storageClass: gp2

auth: 
  database: my_database 
  username: tim
  existingSecret: mysql-secret